version: "3"
services:
  gateway:
    image: ${PULL_REP}/wiseman-gateway
    restart: always
    depends_on:
      - upms
      - auth
    # 端口映射
    ports:
      - 9999:9999
    environment:
      "log.file.path": /thor-gateway/logs/thor-gateway.log
    env_file:
      - env/wsm.env
    volumes:
      - /data/deploy/data/thor/logs:/thor-gateway/logs
    networks:
      - wiseman_net
  auth:
    image: ${PULL_REP}/wiseman-auth
    restart: always
    depends_on:
      - upms
    # 端口映射
    ports:
      - 3000:3000
    environment:
      "log.file.path": /thor-auth/logs/thor-auth.log
    env_file:
      - env/wsm.env
    volumes:
      - /data/deploy/data/thor/logs:/thor-auth/logs
    networks:
      - wiseman_net
  upms:
    image: ${PULL_REP}/wiseman-upms
    restart: always
    # 端口映射
    ports:
      - 4000:4000
    # 容器权限
    # 参数设置
    environment:
      "log.file.path": /thor-upms/logs/thor-upms.log
    env_file:
      - env/wsm.env
    volumes:
      - /data/deploy/data/thor/logs:/thor-upms/logs
    networks:
      - wiseman_net
networks:
  wiseman_net:
    driver: bridge
