version: '3'
services:
  grafana:
    image: images.ideerworld.com/mid/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /home/deploy/grafana:/var/lib/grafana
    environment:
    - GF_SMTP_ENABLED=true
    - GF_SMTP_HOST=smtp.qq.com:587
    - GF_SMTP_USER=a3820671978819@qq.com
    - GF_SMTP_PASSWORD=dxcgcjhcwtzbbhei
    - GF_SMTP_FROM_ADDRESS=a3820671978819@qq.com
    - GF_SMTP_SKIP_VERIFY=true  
    restart: always

  prometheus:
    image: images.ideerworld.com/mid/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/deploy/prometheus:/prometheus
      - /home/deploy/configuration/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
