spring:
  application:
    name: Djva
  datasource:
    username: ${MYSQL_OSS_USER:root}
    password: ${MYSQL_OSS_PWD:123456}
    url: jdbc:mysql://106.52.158.70:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  liquibase:
    change-log: classpath:/db/changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true