--liquibase formatted sql logicalFilePath:changelog-v1.0.0.sql

--changeset hou yong:1
--comment: add oms_reservation_order table
-- thor_oss.oms_reservation_order definition

CREATE TABLE `oms_reservation_order` (
                                         `id` bigint NOT NULL AUTO_INCREMENT,
                                         `reservation_order_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0' COMMENT '预约订单code',
                                         `phone` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0' COMMENT '手机号码',
                                         `member_id` bigint NOT NULL DEFAULT '0' COMMENT '用户id',
                                         `start_time` datetime NOT NULL COMMENT '预约开始时间',
                                         `end_time` datetime NOT NULL COMMENT '预约结束时间',
                                         `reservation_fee` decimal(10,2) DEFAULT NULL COMMENT '预约支付金额',
                                         `actual_fee` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '实际支付金额',
                                         `refund_fee` decimal(10,2) DEFAULT '0.00' COMMENT '退款金额',
                                         `refund_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '退款payCode',
                                         `refund_status` tinyint DEFAULT '0' COMMENT '退款状态 0：不涉及，1：成功，2：退款中，3：失败',
                                         `status` int NOT NULL DEFAULT '0' COMMENT '订单状态：0：待支付、1，支付中，2：预约中、3：已取消、4：已完成、5：异常，6：已退款',
                                         `artificial_status` int NOT NULL DEFAULT '0' COMMENT '是否人工介入 0：未介入，1：已介入',
                                         `update_time` datetime DEFAULT NULL COMMENT '更新时间',
                                         `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                         `pay_type` int NOT NULL DEFAULT '0' COMMENT '支付方式0：余额，1：预付费，2：预付费，余额',
                                         `tenant_id` int NOT NULL DEFAULT '0' COMMENT '租户id',
                                         `operator_id` int NOT NULL DEFAULT '0' COMMENT '运营商id',
                                         `site_table_id` bigint NOT NULL DEFAULT '0' COMMENT '站点id',
                                         `charging_station_id` bigint NOT NULL DEFAULT '0' COMMENT '充电桩ID',
                                         `connector_id` bigint NOT NULL DEFAULT '0' COMMENT '充电枪id',
                                         `settlement_time` datetime DEFAULT NULL COMMENT '结算时间',
                                         `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除',
                                         `creator` bigint DEFAULT NULL COMMENT '创建人',
                                         `order_id` bigint DEFAULT NULL COMMENT '充电订单id',
                                         `order_type` int DEFAULT '0' COMMENT '订单类型1：充电，2：占位',
                                         `user_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '个人/企业',
                                         `order_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '订单code',
                                         `reservation_time` datetime NOT NULL COMMENT '预约时间',
                                         `invoice_status` int DEFAULT NULL COMMENT '发票状态：0：未开票、1：开票中、2：已开票',
                                         `refund_time` datetime DEFAULT NULL COMMENT '退款时间',
                                         `transaction_id` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '支付 退款 transcation',
                                         `pay_channel` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '支付方式',
                                         `after_sales_reason` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '客服处理原因',
                                         `after_sales_remark` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '客服处理备注',
                                         `after_sales_amount` decimal(10,2) DEFAULT '0.00' COMMENT '客服服务退款金额',
                                         `parking_space_id` bigint DEFAULT NULL COMMENT '车位id',
                                         `parking_space_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '停车位名称',
                                         `connector_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '充电枪名称',
                                         `site_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '充电场站',
                                         `charging_station_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                                         `connector_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '充电枪code',
                                         `operator_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '运营商名称',
                                         `command_status` int DEFAULT NULL COMMENT '0:未下发，1:下发成功，2:下发失败',
                                         `charge_expiry_time` datetime DEFAULT NULL COMMENT '预约充电结束时间',
                                         `cancel_command_status` int DEFAULT '0' COMMENT '0:未下发，1:下发成功，2:下发失败',
                                         `evse_id` int DEFAULT NULL,
                                         PRIMARY KEY (`id`),
                                         UNIQUE KEY `oms_reservation_order_unique` (`reservation_order_code`),
                                         KEY `oms_reservation_order_phone_IDX` (`phone`) USING BTREE,
                                         KEY `oms_reservation_order_reservation_order_code_IDX` (`reservation_order_code`) USING BTREE,
                                         KEY `oms_reservation_order_order_code_IDX` (`order_code`) USING BTREE,
                                         KEY `oms_reservation_order_create_time_IDX` (`create_time`) USING BTREE,
                                         KEY `oms_reservation_order_status_IDX` (`status`) USING BTREE,
                                         KEY `oms_reservation_order_site_id_IDX` (`site_table_id`) USING BTREE,
                                         KEY `oms_reservation_order_charging_station_id_IDX` (`charging_station_id`) USING BTREE,
                                         KEY `oms_reservation_order_settlement_time_IDX` (`settlement_time`) USING BTREE,
                                         KEY `oms_reservation_order_reservation_time_IDX` (`reservation_time`) USING BTREE,
                                         KEY `oms_reservation_order_tenant_id_IDX` (`tenant_id`) USING BTREE,
                                         KEY `oms_reservation_order_start_time_IDX` (`start_time`) USING BTREE,
                                         KEY `oms_reservation_order_end_time_IDX` (`end_time`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=147 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='预约订单表';
--rollback alter table oms_reservation_order drop ;


